// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow to automatically find and apply album art to music files using AI.
 *
 * - generateAlbumArt - A function that handles the album art generation process.
 * - GenerateAlbumArtInput - The input type for the generateAlbumArt function.
 * - GenerateAlbumArtOutput - The return type for the generateAlbumArt function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const GenerateAlbumArtInputSchema = z.object({
  songTitle: z.string().describe('The title of the song.'),
  artistName: z.string().describe('The name of the artist.'),
  albumName: z.string().optional().describe('The name of the album, if available.'),
});
export type GenerateAlbumArtInput = z.infer<typeof GenerateAlbumArtInputSchema>;

const GenerateAlbumArtOutputSchema = z.object({
  albumArtUrl: z.string().describe('The URL of the generated album art.'),
});
export type GenerateAlbumArtOutput = z.infer<typeof GenerateAlbumArtOutputSchema>;

export async function generateAlbumArt(input: GenerateAlbumArtInput): Promise<GenerateAlbumArtOutput> {
  return generateAlbumArtFlow(input);
}

const generateAlbumArtPrompt = ai.definePrompt({
  name: 'generateAlbumArtPrompt',
  input: {
    schema: z.object({
      songTitle: z.string().describe('The title of the song.'),
      artistName: z.string().describe('The name of the artist.'),
      albumName: z.string().optional().describe('The name of the album, if available.'),
    }),
  },
  output: {
    schema: z.object({
      albumArtUrl: z.string().describe('The URL of the generated album art.'),
    }),
  },
  prompt: `You are an AI assistant specializing in finding album art for music files.
  Given the song title, artist name, and album name (if available), find a suitable album art URL.
  Return the URL of the album art.

  Song Title: {{{songTitle}}}
  Artist Name: {{{artistName}}}
  Album Name: {{#if albumName}}{{{albumName}}}{{else}}Not Available{{/if}}
  `,
});

const generateAlbumArtFlow = ai.defineFlow<
  typeof GenerateAlbumArtInputSchema,
  typeof GenerateAlbumArtOutputSchema
>({
  name: 'generateAlbumArtFlow',
  inputSchema: GenerateAlbumArtInputSchema,
  outputSchema: GenerateAlbumArtOutputSchema,
}, async input => {
  const {output} = await generateAlbumArtPrompt(input);
  return output!;
});